services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.app:app --host 0.0.0.0 --port 10000
    routes:
      - type: https
        prefix: /  
        target: 10000 
