services:
  - name: web-service
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: REDIS_URL
        sync: false # Can be set via the Render Dashboard
      - key: CELERY_BROKER_URL
        value: "$REDIS_URL"
      - key: CELERY_RESULT_BACKEND
        value: "$REDIS_URL"

  - name: celery-worker
    type: worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A api.celery:app worker --loglevel=info"
    envVars:
      - key: CELERY_BROKER_URL
        value: "$REDIS_URL"
      - key: CELERY_RESULT_BACKEND
        value: "$REDIS_URL"

  - type: redis
    name: redis-be
    plan: free
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
